"""
Prometheus metrics instrumentation for SwanEVAL.

Exposes /metrics endpoint for Prometheus scraping.
Instruments: HTTP requests, task execution, model calls, evaluations.
"""

from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    Info,
)

# ── App info ─────────────────────────────────────────────────────
app_info = Info("swaneval", "SwanEVAL application info")

# ── HTTP request metrics ─────────────────────────────────────────
http_requests_total = Counter(
    "swaneval_http_requests_total",
    "Total HTTP requests",
    ["method", "endpoint", "status"],
)
http_request_duration_seconds = Histogram(
    "swaneval_http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["method", "endpoint"],
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)

# ── Task metrics ─────────────────────────────────────────────────
tasks_total = Counter(
    "swaneval_tasks_total",
    "Total tasks by final status",
    ["status"],
)
tasks_running = Gauge(
    "swaneval_tasks_running",
    "Currently running tasks",
)
task_duration_seconds = Histogram(
    "swaneval_task_duration_seconds",
    "Task execution duration in seconds",
    buckets=(1, 5, 10, 30, 60, 120, 300, 600, 1800, 3600),
)
task_prompts_processed = Counter(
    "swaneval_task_prompts_processed_total",
    "Total prompts processed across all tasks",
)

# ── Model call metrics ───────────────────────────────────────────
model_calls_total = Counter(
    "swaneval_model_calls_total",
    "Total model API calls",
    ["model_name", "status"],
)
model_call_duration_seconds = Histogram(
    "swaneval_model_call_duration_seconds",
    "Model API call duration in seconds",
    ["model_name"],
    buckets=(0.1, 0.5, 1, 2, 5, 10, 30, 60, 120),
)
model_tokens_generated = Counter(
    "swaneval_model_tokens_generated_total",
    "Total tokens generated by models",
    ["model_name"],
)

# ── Evaluation metrics ───────────────────────────────────────────
evaluations_total = Counter(
    "swaneval_evaluations_total",
    "Total criterion evaluations",
    ["criterion_type", "status"],
)
evaluation_score = Histogram(
    "swaneval_evaluation_score",
    "Distribution of evaluation scores",
    ["criterion_type"],
    buckets=(0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
)

# ── Dataset import metrics ───────────────────────────────────────
dataset_imports_total = Counter(
    "swaneval_dataset_imports_total",
    "Total dataset imports",
    ["source", "status"],
)

# ── Resource gauges ──────────────────────────────────────────────
registered_models = Gauge(
    "swaneval_registered_models",
    "Number of registered models",
)
registered_datasets = Gauge(
    "swaneval_registered_datasets",
    "Number of registered datasets",
)
registered_criteria = Gauge(
    "swaneval_registered_criteria",
    "Number of registered criteria",
)
registered_users = Gauge(
    "swaneval_registered_users",
    "Number of registered users",
)
